machine:
  network:
    nameservers:
      - 192.168.14.3
  install:
    disk: /dev/sda
  time:
    servers:
      - 1.ru.pool.ntp.org
      - 2.ru.pool.ntp.org
      - 3.ru.pool.ntp.org
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true