apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
data:
  traefik.yml: |
    logs:
      general:
        level: ERROR

    ports:
      web:

    ingressRoute:
      dashboard:
        enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true