apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.11
          args:
            - --api.insecure
            - --entryPoints.websecure.address=:443
            - --providers.kubernetesingress
            # - --serversTransport.insecureSkipVerify=true
          ports:
            - name: weblocal
              containerPort: 443
            - name: dashboard
              containerPort: 8080
