apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    # - name: web
    #   targetPort: web
    #   port: 80
    - name: local
      targetPort: 443
      port: 443
    - name: websecure
      targetPort: 444
      port: 444