apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl-certs
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ssl-certs
  nfs:
    server: 192.168.14.11
    path: /mnt/main/k3s-storage/ssl-certs