apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
          - name: webserver-cm
            mountPath: /etc/nginx
          - name: temp
            mountPath: /var/cache/nginx/client_temp
          - name: local
            mountPath: /usr/share/nginx/html
      volumes:
      - name: webserver-cm
        configMap:
          name: webserver-cm
      - name: local
        persistentVolumeClaim:
          claimName: nfs
      - name: temp
        persistentVolumeClaim:
          claimName: nfs_temp