apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: default
  labels:
    app: navidrome
spec:
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        env:
          - name: ND_SCANSCHEDULE
            value: 1h
          - name: ND_LOGLEVEL
            value : info
          - name: ND_SESSIONTIMEOUT
            value : 24h
          - name: ND_BASEURL
            value : "navidrome.sugjo.dev"
        ports:
        - containerPort: 4533
