apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: default
  labels:
    app.kubernetes.io/name: navidrome
spec:
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: navidrome
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        ports:
        - containerPort: 4533
