apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  labels:
    name: navidrome
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: local, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Music
    gethomepage.dev/icon: navidrome.png
    gethomepage.dev/name: Navidrome
spec:
  rules:
  - host: "navidrome.sugjo.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: navidrome
            port:
              number: 80

  tls:
  - secretName: sugjodev
