apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sugjodev
  namespace: default
spec:
  secretName: sugjodev
  issuerRef:
    name: regru-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.sugjo.dev"