apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: regru-dns
  namespace: cert-manager
spec:
  acme:
    # Email address used for ACME registration. REPLACE THIS WITH YOUR EMAIL!
    email: akhmadeev.ilya@yandex.ru
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-letsencrypt-private-key
    solvers:
      - dns01:
          webhook:
            config:
              regruPasswordSecretRef:
                name: regru-password
                key: REGRU_PASSWORD
            groupName: acme.regru.ru
            solverName: regru-dns