clusterName: teleport.sugjo.dev
proxyListenerMode: multiplex
service:
  type: ClusterIP
annotations:
  ingress:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: local
    traefik.ingress.kubernetes.io/router.tls: "true"
ingress:
  enabled: true
tls:
  existingSecretName: "sugjodev"