version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: "1.18.2"
      FORGE_VERSION: "40.2.9"
      MEMORY: "8G"
      MOTD: "\u00a74\u0414\u0440\u0435\u0432\u043d\u0438\u0435 \u0440\u0443\u0441\u044b\u00a7r, \u0432\u043f\u0435\u0440\u0451\u0434!\n\u00a72\u042f\u0449\u0435\u0440\u044b\u00a7r, \u0441\u043e\u0441\u0430\u0442\u044c!"
      JVM_OPTS: -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
      ONLINE_MODE: FALSE
      VIEW_DISTANCE: 5
      SIMULATION_DISTANCE: 5
      ENABLE_QUERY: TRUE
      PVP: FALSE
    volumes:
      - /docker/volumes/minecraft/modpacks/DC:/data
    restart: always
