version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/volumes/nextcloud/appdata:/config
      - /docker/volumes/nextcloud:/data
      - /docker/volumes/public/media:/app/www/public/media
    ports:
      - 449:443
    restart: unless-stopped