apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.releases.teleport.dev
      chart: teleport
      path: "HelmCharts/teleport/"
      helm:
        releaseName: teleport
        valueFiles:
          - $values/HelmCharts/teleport/values.yml
    - repoURL: git@github.com:sugjo/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"