apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      path: "HelmCharts/traefik/"
      targetRevision: 26.1.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/HelmChart/traefik/values.yml
    - repoURL: git@github.com:sugjo/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik