apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path   : "prod/applications"
    repoURL: "https://github.com/sugjo/homelab"
    targetRevision: HEAD
  destination:
    name     : in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true