apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: default
spec:
  entryPoints:
    - local
  routes:
    - match: Host(`proxmox.sugjo.dev`)
      kind: Rule
      services:
        - name: external-service
          kind: Service
          port: 80
  tls:
    secretName: sugjodev