kind: Service
apiVersion: v1
metadata:
  name: external-service
spec:
  type: ExternalName
  ports:
    - name: external-service
      port: 8006
  externalName: 192.168.14.10
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik