apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : helm-webapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: argocd
  source:
    repoURL       : "git@github.com:sugjo/argo-examples.git"
    path          : "helm-webapp"
    targetRevision: "HEAD"
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true