apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: "2.0.1"
    helm:
      valueFiles:
        - values/homepage.yaml
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true