apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    server: in-cluster
    namespace: argocd
  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: "HEAD"
    helm:
      valueFiles:
        - ./values/homepage.yaml
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true