apiVersion: v1
kind: Secret
metadata:
  name: "${name_lower}-repo"
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: "${name}"
  url: "${repoURL}"
  sshPrivateKey: |
%{ for line in ssh_key ~}
    ${line}
%{ endfor ~}