apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    kube-vip.io/loadbalancerIPs: 192.168.14.75
    # traefik.ingress.kubernetes.io/router.middlewares: local-only@kubernetes

spec:
  rules:
  - host: "whoami.sugjo.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-service
            port:
              number: 80
  tls:
  - hosts:
    - whoami.sugjo.dev
    secretName: sugjodev