apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  labels:
    app: bind9

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          image: ubuntu/bind9:latest
          ports:
            - containerPort: 53